app:
  version: 1.0.1

spring:
  servlet:
    multipart:
      maxFileSize: 30MB # 파일 하나의 최대 크기
      maxRequestSize: 100MB  # 한 번에 최대 업로드 가능 용량
  config:
    import: classpath:application-private.yml
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.id} # 앱키 -> REST API 키
            client-secret: ${kakao.secret} # 카카오 로그인 -> 보안 -> Client Secret 코드
            authorization-grant-type: authorization_code
            redirect-uri: ${kakao.redirect}
            client-authentication-method: client_secret_post # POST 사용 불가 (setRequestEntityConverter를 사용하여 POST를 지원하는 인스턴스를 제공해야 함.)
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # "인가 코드 받기" 항목
            token-uri: https://kauth.kakao.com/oauth/token # "토큰 받기" 항목
            user-info-uri: https://kapi.kakao.com/v2/user/me # "사용자 정보 가져오기" 항목
            user-name-attribute: id # 식별자 . 카카오의 경우 "id" 사용

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create # create none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug


springdoc:
  swagger-ui:
    path: /swagger-ui.html # 스웨거 접근 경로
    groups-order: DESC # API 그룹 표시 순서

    # alpha: 알파벳 순 정렬
    # method: OpenAPI specification file에 원하는 태그 정렬 방식 직접 기재
    tags-sorter: alpha # 태그 정렬 순서.

    operationsSorter: method # 컨트롤러 정렬 순서
    disable-swagger-default-url: true # swagger-ui default url인 petstore html의 비활성화 설정
    display-request-duration: true # swagger-ui default url인 petstore html의 비활성화 설정
  api-docs:
    path: /api-docs # openAPI 접근 경로. default 값은 /v3/api-docs 이다.
  show-actuator: true # Spring Actuator의 endpoint까지 보여줄 것인지?
  default-consumes-media-type: application/json # request media type 의 기본 값
  default-produces-media-type: application/json # response media type 의 기본 값
  paths-to-match: /api/** # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.

cloud:
  aws:
    s3:
      bucket: ${s3.bucket}
    stack:
      auto: false
    region.static: ${s3.region}
    credentials:
      accessKey: ${s3.accessKey}
      secretKey: ${s3.secretKey}