app:
  version: 1.0.1

spring:
  profiles:
    include: private
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client.id} # 앱키 -> REST API 키
            client-secret: ${kakao.client.secret} # 카카오 로그인 -> 보안 -> Client Secret 코드
            authorization-grant-type: authorization_code
            redirect-uri: ${kakao.redirect-uri}
            client-authentication-method: client_secret_post # POST 사용 불가 (setRequestEntityConverter를 사용하여 POST를 지원하는 인스턴스를 제공해야 함.)
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # "인가 코드 받기" 항목
            token-uri: https://kauth.kakao.com/oauth/token # "토큰 받기" 항목
            user-info-uri: https://kapi.kakao.com/v2/user/me # "사용자 정보 가져오기" 항목
            user-name-attribute: id # 식별자 . 카카오의 경우 "id" 사용

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/alpha?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: ss64267844!@
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create # create none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug


springdoc:
  swagger-ui:
    path: /swagger-ui.html # 스웨거 접근 경로
    groups-order: DESC # API 그룹 표시 순서

    # alpha: 알파벳 순 정렬
    # method: OpenAPI specification file에 원하는 태그 정렬 방식 직접 기재
    tags-sorter: alpha # 태그 정렬 순서.

    operationsSorter: method # 컨트롤러 정렬 순서
    disable-swagger-default-url: true # swagger-ui default url인 petstore html의 비활성화 설정
    display-request-duration: true # swagger-ui default url인 petstore html의 비활성화 설정
  api-docs:
    path: /api-docs # openAPI 접근 경로. default 값은 /v3/api-docs 이다.
  show-actuator: true # Spring Actuator의 endpoint까지 보여줄 것인지?
  default-consumes-media-type: application/json # request media type 의 기본 값
  default-produces-media-type: application/json # response media type 의 기본 값
  paths-to-match: /api/** # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.

---
kakao:
  client:
    id: bf112ec286fcdd432da901824631453f
    secret: SwsFDoYP84xf3hXOCK8CcusqtB6nzE0p
  redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"


jwt:
  # 1Dawoon2HyeonJin3HanGyeol4Subin5Seungjoon6Geon를 Base64로 인코딩함.
  secret-key: MURhd29vbjJIeWVvbkppbjNIYW5HeWVvbDRTdWJpbjVTZXVuZ2pvb242R2Vvbg==
  access-token:
    expiration: 43200 # 12시간
  refresh-token:
    expiration: 1209600 # 14일

cloud:
  aws:
    s3:
      bucket: alpha
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAT6UNPE54SCXQWHVS
      secretKey: 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