name: CI / CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시
  application-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # 지정한 저장소(현재 REPO)에서 코드를 워크플로우 환경으로 가져오도록 하는 github action
    steps:
    - uses: actions/checkout@v4
    
    # 1. Java 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # 2. application-private.yml 설정
    - name: Set application-private.yml file
      run: |  
        # application-private.yml 파일 생성
        cd ./src/main/resources
        touch ./application-private.yml

        # GitHub-Actions 에서 설정한 값을 application-private.yml 파일에 쓰기
        echo "${{ secrets.APPLICATION_YML }}" >> ./application-private.yml
      shell: bash

    # 3. gradle을 통해 소스를 빌드.
    - name: Build with Gradle
      run: |
          chmod +x ./gradlew
          ./gradlew clean build

    # { username/repository } 로 빌드 & . 이 의미하는 것은 Dockerfile의 경로를 의미함.
    - name: Docker build & push to docker repo
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_USER }}/alpha_dlink . 
        docker push ${{ secrets.DOCKER_REPO }}/alpha_dlink

  # 의존성 그래프 테스트
  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
